CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node 8  train_sft.py \
    --model_type llama \
    --model_name_or_path /data/searchgpt/pretrained_models/llama-7b-hf \
    --train_file_dir data/finetune/opendata \
    --validation_file_dir data/finetune/opendata \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --use_peft False \
    --do_train \
    --do_eval \
    --fp16 \
    --max_train_samples 100000 \
    --max_eval_samples 10 \
    --num_train_epochs 1 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --max_source_length 256 \
    --max_target_length 512 \
    --output_dir outputs-sft-v1-freeze \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True
