deepspeed --num_gpus=2  train.py \
    --model_name_or_path /data/searchgpt/pretrained_models/bloomz-7b1 \
    --data_path opendata \
    --bf16 True \
    --output_dir output_dir_7b \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --deepspeed "./configs/default_offlload_zero2.json" \
    --tf32 False
