deepspeed --num_gpus=8  step3_train_sft_v2.py \
    --model_name_or_path /data/searchgpt/yq/GoGPT/llama2-7b-sft-alpaca_gpt4-v2/checkpoint-2500 \
    --data_path /data/searchgpt/yq/GoGPT/data/finetune/filterd/ \
    --bf16 True \
    --output_dir llama2-7b-sft-filterd-v3 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --logging_steps 10 \
    --deepspeed "./configs/default_offlload_zero2.json" \
    --tf32 True \
    --model_max_length 4096
